'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Spinner } from '@/components/ui/spinner';
import { Download } from 'lucide-react';

interface AnalysisResult {
  summary: string;
  sentiment: {
    label: 'positive' | 'neutral' | 'negative';
    score: number;
  };
  topics: string[];
  readability: {
    grade: string;
    level: string;
  };
}

const WORD_MIN = 50;

export function AnalyzeText() {
  const [text, setText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState('');

  const charCount = text.length;
  const wordCount = text.trim().split(/\s+/).filter(Boolean).length;
  const isValidLength = wordCount >= WORD_MIN;

  const handleAnalyze = async () => {
    if (!isValidLength) {
      setError(`Please enter at least ${WORD_MIN} words`);
      return;
    }

    setError('');
    setIsLoading(true);

    try {
      // Simulate API call
      await new Promise((resolve) => setTimeout(resolve, 2000));

      // Mock analysis result
      const sentimentScores = [
        { label: 'positive' as const, score: 0.72 },
        { label: 'neutral' as const, score: 0.65 },
        { label: 'negative' as const, score: 0.28 },
      ];
      const randomSentiment =
        sentimentScores[Math.floor(Math.random() * sentimentScores.length)];

      setResult({
        summary: `This text discusses ${text.split(/\s+/).slice(0, 5).join(' ')}... The content appears to be well-structured and engaging, providing valuable insights on the topic.`,
        sentiment: randomSentiment,
        topics: ['AI', 'Text Analysis', 'NLP', 'Technology', 'Data'],
        readability: {
          grade: '8th',
          level: 'Easy to Read',
        },
      });
    } catch (err) {
      setError('Failed to analyze text. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleExport = () => {
    if (!result) return;

    const content = `TEXT ANALYSIS REPORT
====================

SUMMARY
${result.summary}

SENTIMENT ANALYSIS
Sentiment: ${result.sentiment.label.charAt(0).toUpperCase() + result.sentiment.label.slice(1)}
Score: ${(result.sentiment.score * 100).toFixed(1)}%

KEY TOPICS
${result.topics.map((topic) => `- ${topic}`).join('\n')}

READABILITY
Grade Level: ${result.readability.grade}
Reading Level: ${result.readability.level}

---
Generated by TextIQ | ${new Date().toLocaleDateString()}`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `analysis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const sentimentEmoji = {
    positive: '😊',
    neutral: '😐',
    negative: '😞',
  };

  return (
    <div className="space-y-6">
      {/* Input Section */}
      <Card>
        <CardHeader>
          <CardTitle>Paste Your Text</CardTitle>
          <CardDescription>Enter at least {WORD_MIN} words for analysis</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-3">
            <Textarea
              placeholder="Paste your text here... minimum 50 words"
              value={text}
              onChange={(e) => {
                setText(e.target.value);
                setError('');
              }}
              className="min-h-64 resize-none"
              disabled={isLoading}
            />

            {/* Counter */}
            <div className="flex items-center justify-between text-sm">
              <div className="space-x-4">
                <span className={wordCount >= WORD_MIN ? 'text-green-600' : 'text-slate-500'}>
                  Words: {wordCount}
                </span>
                <span className="text-slate-500">Characters: {charCount}</span>
              </div>
              <span className={wordCount >= WORD_MIN ? 'text-green-600 font-medium' : 'text-red-500 font-medium'}>
                {isValidLength ? 'Ready to analyze' : `${Math.max(0, WORD_MIN - wordCount)} more words needed`}
              </span>
            </div>

            {/* Error Message */}
            {error && <div className="text-sm text-red-500">{error}</div>}
          </div>

          {/* Analyze Button */}
          <Button
            onClick={handleAnalyze}
            disabled={!isValidLength || isLoading}
            size="lg"
            className="w-full"
          >
            {isLoading ? (
              <>
                <Spinner className="mr-2 h-4 w-4" />
                Analyzing...
              </>
            ) : (
              'Analyze with AI'
            )}
          </Button>
        </CardContent>
      </Card>

      {/* Results Section */}
      {(isLoading || result) && (
        <div className="space-y-6">
          {isLoading ? (
            <>
              {/* Skeleton Loading */}
              <Card>
                <CardHeader>
                  <Skeleton className="h-6 w-32" />
                </CardHeader>
                <CardContent>
                  <Skeleton className="h-20 w-full" />
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <Skeleton className="h-6 w-40" />
                </CardHeader>
                <CardContent className="space-y-3">
                  <Skeleton className="h-8 w-full" />
                  <Skeleton className="h-4 w-32" />
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <Skeleton className="h-6 w-32" />
                </CardHeader>
                <CardContent className="flex gap-2">
                  <Skeleton className="h-8 w-20" />
                  <Skeleton className="h-8 w-20" />
                  <Skeleton className="h-8 w-20" />
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <Skeleton className="h-6 w-40" />
                </CardHeader>
                <CardContent>
                  <Skeleton className="h-12 w-full" />
                </CardContent>
              </Card>
            </>
          ) : result ? (
            <>
              {/* Summary Card */}
              <Card>
                <CardHeader>
                  <CardTitle>Summary</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-slate-600 dark:text-slate-400">{result.summary}</p>
                </CardContent>
              </Card>

              {/* Sentiment Card */}
              <Card>
                <CardHeader>
                  <CardTitle>Sentiment Analysis</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-center gap-4">
                    <span className="text-4xl" suppressHydrationWarning>
                      {sentimentEmoji[result.sentiment.label]}
                    </span>
                    <div className="flex-1">
                      <div className="mb-2 flex items-center justify-between">
                        <span className="font-medium capitalize">{result.sentiment.label}</span>
                        <span className="text-sm font-semibold">
                          {(result.sentiment.score * 100).toFixed(1)}%
                        </span>
                      </div>
                      <div className="h-3 w-full overflow-hidden rounded-full bg-slate-200 dark:bg-slate-700">
                        <div
                          className={`h-full transition-all duration-500 ${
                            result.sentiment.label === 'positive'
                              ? 'bg-green-500'
                              : result.sentiment.label === 'neutral'
                                ? 'bg-blue-500'
                                : 'bg-red-500'
                          }`}
                          style={{ width: `${result.sentiment.score * 100}%` }}
                        />
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Key Topics */}
              <Card>
                <CardHeader>
                  <CardTitle>Key Topics</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2">
                    {result.topics.map((topic) => (
                      <Badge key={topic} variant="secondary">
                        {topic}
                      </Badge>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {/* Readability Card */}
              <Card>
                <CardHeader>
                  <CardTitle>Readability Score</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    <div className="flex items-center justify-between rounded-lg bg-slate-50 p-4 dark:bg-slate-900">
                      <span className="font-medium">Grade Level</span>
                      <span className="text-2xl font-bold text-blue-600">{result.readability.grade}</span>
                    </div>
                    <div className="flex items-center justify-between rounded-lg bg-slate-50 p-4 dark:bg-slate-900">
                      <span className="font-medium">Reading Level</span>
                      <span className="text-lg font-semibold">{result.readability.level}</span>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Export Button */}
              <Button
                onClick={handleExport}
                variant="outline"
                size="lg"
                className="w-full"
              >
                <Download className="mr-2 h-4 w-4" />
                Export as Text File
              </Button>
            </>
          ) : null}
        </div>
      )}
    </div>
  );
}
